// %BANNER_BEGIN%
// ---------------------------------------------------------------------
// %COPYRIGHT_BEGIN%
//
// Copyright (c) 2017 Magic Leap, Inc. (COMPANY) All Rights Reserved.
// Magic Leap, Inc. Confidential and Proprietary
//
// NOTICE: All information contained herein is, and remains the property
// of COMPANY. The intellectual and technical concepts contained herein
// are proprietary to COMPANY and may be covered by U.S. and Foreign
// Patents, patents in process, and are protected by trade secret or
// copyright law. Dissemination of this information or reproduction of
// this material is strictly forbidden unless prior written permission is
// obtained from COMPANY. Access to the source code contained herein is
// hereby forbidden to anyone except current COMPANY employees, managers
// or contractors who have executed Confidentiality and Non-disclosure
// agreements explicitly covering such access.
//
// The copyright notice above does not evidence any actual or intended
// publication or disclosure of this source code, which includes
// information that is confidential and/or proprietary, and is a trade
// secret, of COMPANY. ANY REPRODUCTION, MODIFICATION, DISTRIBUTION,
// PUBLIC PERFORMANCE, OR PUBLIC DISPLAY OF OR THROUGH USE OF THIS
// SOURCE CODE WITHOUT THE EXPRESS WRITTEN CONSENT OF COMPANY IS
// STRICTLY PROHIBITED, AND IN VIOLATION OF APPLICABLE LAWS AND
// INTERNATIONAL TREATIES. THE RECEIPT OR POSSESSION OF THIS SOURCE
// CODE AND/OR RELATED INFORMATION DOES NOT CONVEY OR IMPLY ANY RIGHTS
// TO REPRODUCE, DISCLOSE OR DISTRIBUTE ITS CONTENTS, OR TO MANUFACTURE,
// USE, OR SELL ANYTHING THAT IT MAY DESCRIBE, IN WHOLE OR IN PART.
//
// %COPYRIGHT_END%
// ---------------------------------------------------------------------
// %BANNER_END%

#pragma once

ML_EXTERN_C_BEGIN

/*! Keycodes defined for Magic Leap platform. */
typedef enum MLKeyCode {
    MLKEYCODE_UNKNOWN                       = 0,
    MLKEYCODE_SOFT_LEFT                     = 1,
    MLKEYCODE_SOFT_RIGHT                    = 2,
    MLKEYCODE_HOME                          = 3,
    MLKEYCODE_BACK                          = 4,
    MLKEYCODE_CALL                          = 5,
    MLKEYCODE_ENDCALL                       = 6,
    MLKEYCODE_0                             = 7,
    MLKEYCODE_1                             = 8,
    MLKEYCODE_2                             = 9,
    MLKEYCODE_3                             = 10,
    MLKEYCODE_4                             = 11,
    MLKEYCODE_5                             = 12,
    MLKEYCODE_6                             = 13,
    MLKEYCODE_7                             = 14,
    MLKEYCODE_8                             = 15,
    MLKEYCODE_9                             = 16,
    MLKEYCODE_STAR                          = 17,
    MLKEYCODE_POUND                         = 18,
    MLKEYCODE_DPAD_UP                       = 19,
    MLKEYCODE_DPAD_DOWN                     = 20,
    MLKEYCODE_DPAD_LEFT                     = 21,
    MLKEYCODE_DPAD_RIGHT                    = 22,
    MLKEYCODE_DPAD_CENTER                   = 23,
    MLKEYCODE_VOLUME_UP                     = 24,
    MLKEYCODE_VOLUME_DOWN                   = 25,
    MLKEYCODE_POWER                         = 26,
    MLKEYCODE_CAMERA                        = 27,
    MLKEYCODE_CLEAR                         = 28,
    MLKEYCODE_A                             = 29,
    MLKEYCODE_B                             = 30,
    MLKEYCODE_C                             = 31,
    MLKEYCODE_D                             = 32,
    MLKEYCODE_E                             = 33,
    MLKEYCODE_F                             = 34,
    MLKEYCODE_G                             = 35,
    MLKEYCODE_H                             = 36,
    MLKEYCODE_I                             = 37,
    MLKEYCODE_J                             = 38,
    MLKEYCODE_K                             = 39,
    MLKEYCODE_L                             = 40,
    MLKEYCODE_M                             = 41,
    MLKEYCODE_N                             = 42,
    MLKEYCODE_O                             = 43,
    MLKEYCODE_P                             = 44,
    MLKEYCODE_Q                             = 45,
    MLKEYCODE_R                             = 46,
    MLKEYCODE_S                             = 47,
    MLKEYCODE_T                             = 48,
    MLKEYCODE_U                             = 49,
    MLKEYCODE_V                             = 50,
    MLKEYCODE_W                             = 51,
    MLKEYCODE_X                             = 52,
    MLKEYCODE_Y                             = 53,
    MLKEYCODE_Z                             = 54,
    MLKEYCODE_COMMA                         = 55,
    MLKEYCODE_PERIOD                        = 56,
    MLKEYCODE_ALT_LEFT                      = 57,
    MLKEYCODE_ALT_RIGHT                     = 58,
    MLKEYCODE_SHIFT_LEFT                    = 59,
    MLKEYCODE_SHIFT_RIGHT                   = 60,
    MLKEYCODE_TAB                           = 61,
    MLKEYCODE_SPACE                         = 62,
    MLKEYCODE_SYM                           = 63,
    MLKEYCODE_EXPLORER                      = 64,
    MLKEYCODE_ENVELOPE                      = 65,
    MLKEYCODE_ENTER                         = 66,
    MLKEYCODE_DEL                           = 67,
    MLKEYCODE_GRAVE                         = 68,
    MLKEYCODE_MINUS                         = 69,
    MLKEYCODE_EQUALS                        = 70,
    MLKEYCODE_LEFT_BRACKET                  = 71,
    MLKEYCODE_RIGHT_BRACKET                 = 72,
    MLKEYCODE_BACKSLASH                     = 73,
    MLKEYCODE_SEMICOLON                     = 74,
    MLKEYCODE_APOSTROPHE                    = 75,
    MLKEYCODE_SLASH                         = 76,
    MLKEYCODE_AT                            = 77,
    MLKEYCODE_NUM                           = 78,
    MLKEYCODE_HEADSETHOOK                   = 79,
    MLKEYCODE_FOCUS                         = 80,
    MLKEYCODE_PLUS                          = 81,
    MLKEYCODE_MENU                          = 82,
    MLKEYCODE_NOTIFICATION                  = 83,
    MLKEYCODE_SEARCH                        = 84,
    MLKEYCODE_MEDIA_PLAY_PAUSE              = 85,
    MLKEYCODE_MEDIA_STOP                    = 86,
    MLKEYCODE_MEDIA_NEXT                    = 87,
    MLKEYCODE_MEDIA_PREVIOUS                = 88,
    MLKEYCODE_MEDIA_REWIND                  = 89,
    MLKEYCODE_MEDIA_FAST_FORWARD            = 90,
    MLKEYCODE_MUTE                          = 91,
    MLKEYCODE_PAGE_UP                       = 92,
    MLKEYCODE_PAGE_DOWN                     = 93,
    MLKEYCODE_PICTSYMBOLS                   = 94,
    MLKEYCODE_SWITCH_CHARSET                = 95,
    MLKEYCODE_BUTTON_A                      = 96,
    MLKEYCODE_BUTTON_B                      = 97,
    MLKEYCODE_BUTTON_C                      = 98,
    MLKEYCODE_BUTTON_X                      = 99,
    MLKEYCODE_BUTTON_Y                      = 100,
    MLKEYCODE_BUTTON_Z                      = 101,
    MLKEYCODE_BUTTON_L1                     = 102,
    MLKEYCODE_BUTTON_R1                     = 103,
    MLKEYCODE_BUTTON_L2                     = 104,
    MLKEYCODE_BUTTON_R2                     = 105,
    MLKEYCODE_BUTTON_THUMBL                 = 106,
    MLKEYCODE_BUTTON_THUMBR                 = 107,
    MLKEYCODE_BUTTON_START                  = 108,
    MLKEYCODE_BUTTON_SELECT                 = 109,
    MLKEYCODE_BUTTON_MODE                   = 110,
    MLKEYCODE_ESCAPE                        = 111,
    MLKEYCODE_FORWARD_DEL                   = 112,
    MLKEYCODE_CTRL_LEFT                     = 113,
    MLKEYCODE_CTRL_RIGHT                    = 114,
    MLKEYCODE_CAPS_LOCK                     = 115,
    MLKEYCODE_SCROLL_LOCK                   = 116,
    MLKEYCODE_META_LEFT                     = 117,
    MLKEYCODE_META_RIGHT                    = 118,
    MLKEYCODE_FUNCTION                      = 119,
    MLKEYCODE_SYSRQ                         = 120,
    MLKEYCODE_BREAK                         = 121,
    MLKEYCODE_MOVE_HOME                     = 122,
    MLKEYCODE_MOVE_END                      = 123,
    MLKEYCODE_INSERT                        = 124,
    MLKEYCODE_FORWARD                       = 125,
    MLKEYCODE_MEDIA_PLAY                    = 126,
    MLKEYCODE_MEDIA_PAUSE                   = 127,
    MLKEYCODE_MEDIA_CLOSE                   = 128,
    MLKEYCODE_MEDIA_EJECT                   = 129,
    MLKEYCODE_MEDIA_RECORD                  = 130,
    MLKEYCODE_F1                            = 131,
    MLKEYCODE_F2                            = 132,
    MLKEYCODE_F3                            = 133,
    MLKEYCODE_F4                            = 134,
    MLKEYCODE_F5                            = 135,
    MLKEYCODE_F6                            = 136,
    MLKEYCODE_F7                            = 137,
    MLKEYCODE_F8                            = 138,
    MLKEYCODE_F9                            = 139,
    MLKEYCODE_F10                           = 140,
    MLKEYCODE_F11                           = 141,
    MLKEYCODE_F12                           = 142,
    MLKEYCODE_NUM_LOCK                      = 143,
    MLKEYCODE_NUMPAD_0                      = 144,
    MLKEYCODE_NUMPAD_1                      = 145,
    MLKEYCODE_NUMPAD_2                      = 146,
    MLKEYCODE_NUMPAD_3                      = 147,
    MLKEYCODE_NUMPAD_4                      = 148,
    MLKEYCODE_NUMPAD_5                      = 149,
    MLKEYCODE_NUMPAD_6                      = 150,
    MLKEYCODE_NUMPAD_7                      = 151,
    MLKEYCODE_NUMPAD_8                      = 152,
    MLKEYCODE_NUMPAD_9                      = 153,
    MLKEYCODE_NUMPAD_DIVIDE                 = 154,
    MLKEYCODE_NUMPAD_MULTIPLY               = 155,
    MLKEYCODE_NUMPAD_SUBTRACT               = 156,
    MLKEYCODE_NUMPAD_ADD                    = 157,
    MLKEYCODE_NUMPAD_DOT                    = 158,
    MLKEYCODE_NUMPAD_COMMA                  = 159,
    MLKEYCODE_NUMPAD_ENTER                  = 160,
    MLKEYCODE_NUMPAD_EQUALS                 = 161,
    MLKEYCODE_NUMPAD_LEFT_PAREN             = 162,
    MLKEYCODE_NUMPAD_RIGHT_PAREN            = 163,
    MLKEYCODE_VOLUME_MUTE                   = 164,
    MLKEYCODE_INFO                          = 165,
    MLKEYCODE_CHANNEL_UP                    = 166,
    MLKEYCODE_CHANNEL_DOWN                  = 167,
    MLKEYCODE_ZOOM_IN                       = 168,
    MLKEYCODE_ZOOM_OUT                      = 169,
    MLKEYCODE_TV                            = 170,
    MLKEYCODE_WINDOW                        = 171,
    MLKEYCODE_GUIDE                         = 172,
    MLKEYCODE_DVR                           = 173,
    MLKEYCODE_BOOKMARK                      = 174,
    MLKEYCODE_CAPTIONS                      = 175,
    MLKEYCODE_SETTINGS                      = 176,
    MLKEYCODE_TV_POWER                      = 177,
    MLKEYCODE_TV_INPUT                      = 178,
    MLKEYCODE_STB_POWER                     = 179,
    MLKEYCODE_STB_INPUT                     = 180,
    MLKEYCODE_AVR_POWER                     = 181,
    MLKEYCODE_AVR_INPUT                     = 182,
    MLKEYCODE_PROG_RED                      = 183,
    MLKEYCODE_PROG_GREEN                    = 184,
    MLKEYCODE_PROG_YELLOW                   = 185,
    MLKEYCODE_PROG_BLUE                     = 186,
    MLKEYCODE_APP_SWITCH                    = 187,
    MLKEYCODE_BUTTON_1                      = 188,
    MLKEYCODE_BUTTON_2                      = 189,
    MLKEYCODE_BUTTON_3                      = 190,
    MLKEYCODE_BUTTON_4                      = 191,
    MLKEYCODE_BUTTON_5                      = 192,
    MLKEYCODE_BUTTON_6                      = 193,
    MLKEYCODE_BUTTON_7                      = 194,
    MLKEYCODE_BUTTON_8                      = 195,
    MLKEYCODE_BUTTON_9                      = 196,
    MLKEYCODE_BUTTON_10                     = 197,
    MLKEYCODE_BUTTON_11                     = 198,
    MLKEYCODE_BUTTON_12                     = 199,
    MLKEYCODE_BUTTON_13                     = 200,
    MLKEYCODE_BUTTON_14                     = 201,
    MLKEYCODE_BUTTON_15                     = 202,
    MLKEYCODE_BUTTON_16                     = 203,
    MLKEYCODE_LANGUAGE_SWITCH               = 204,
    MLKEYCODE_MANNER_MODE                   = 205,
    MLKEYCODE_3D_MODE                       = 206,
    MLKEYCODE_CONTACTS                      = 207,
    MLKEYCODE_CALENDAR                      = 208,
    MLKEYCODE_MUSIC                         = 209,
    MLKEYCODE_CALCULATOR                    = 210,
    MLKEYCODE_ZENKAKU_HANKAKU               = 211,
    MLKEYCODE_EISU                          = 212,
    MLKEYCODE_MUHENKAN                      = 213,
    MLKEYCODE_HENKAN                        = 214,
    MLKEYCODE_KATAKANA_HIRAGANA             = 215,
    MLKEYCODE_YEN                           = 216,
    MLKEYCODE_RO                            = 217,
    MLKEYCODE_KANA                          = 218,
    MLKEYCODE_ASSIST                        = 219,
    MLKEYCODE_BRIGHTNESS_DOWN               = 220,
    MLKEYCODE_BRIGHTNESS_UP                 = 221,
    MLKEYCODE_MEDIA_AUDIO_TRACK             = 222,
    MLKEYCODE_SLEEP                         = 223,
    MLKEYCODE_WAKEUP                        = 224,
    MLKEYCODE_PAIRING                       = 225,
    MLKEYCODE_MEDIA_TOP_MENU                = 226,
    MLKEYCODE_11                            = 227,
    MLKEYCODE_12                            = 228,
    MLKEYCODE_LAST_CHANNEL                  = 229,
    MLKEYCODE_TV_DATA_SERVICE               = 230,
    MLKEYCODE_VOICE_ASSIST                  = 231,
    MLKEYCODE_TV_RADIO_SERVICE              = 232,
    MLKEYCODE_TV_TELETEXT                   = 233,
    MLKEYCODE_TV_NUMBER_ENTRY               = 234,
    MLKEYCODE_TV_TERRESTRIAL_ANALOG         = 235,
    MLKEYCODE_TV_TERRESTRIAL_DIGITAL        = 236,
    MLKEYCODE_TV_SATELLITE                  = 237,
    MLKEYCODE_TV_SATELLITE_BS               = 238,
    MLKEYCODE_TV_SATELLITE_CS               = 239,
    MLKEYCODE_TV_SATELLITE_SERVICE          = 240,
    MLKEYCODE_TV_NETWORK                    = 241,
    MLKEYCODE_TV_ANTENNA_CABLE              = 242,
    MLKEYCODE_TV_INPUT_HDMI_1               = 243,
    MLKEYCODE_TV_INPUT_HDMI_2               = 244,
    MLKEYCODE_TV_INPUT_HDMI_3               = 245,
    MLKEYCODE_TV_INPUT_HDMI_4               = 246,
    MLKEYCODE_TV_INPUT_COMPOSITE_1          = 247,
    MLKEYCODE_TV_INPUT_COMPOSITE_2          = 248,
    MLKEYCODE_TV_INPUT_COMPONENT_1          = 249,
    MLKEYCODE_TV_INPUT_COMPONENT_2          = 250,
    MLKEYCODE_TV_INPUT_VGA_1                = 251,
    MLKEYCODE_TV_AUDIO_DESCRIPTION          = 252,
    MLKEYCODE_TV_AUDIO_DESCRIPTION_MIX_UP   = 253,
    MLKEYCODE_TV_AUDIO_DESCRIPTION_MIX_DOWN = 254,
    MLKEYCODE_TV_ZOOM_MODE                  = 255,
    MLKEYCODE_TV_CONTENTS_MENU              = 256,
    MLKEYCODE_TV_MEDIA_CONTEXT_MENU         = 257,
    MLKEYCODE_TV_TIMER_PROGRAMMING          = 258,
    MLKEYCODE_HELP                          = 259,
    MLKEYCODE_NAVIGATE_PREVIOUS             = 260,
    MLKEYCODE_NAVIGATE_NEXT                 = 261,
    MLKEYCODE_NAVIGATE_IN                   = 262,
    MLKEYCODE_NAVIGATE_OUT                  = 263,
    MLKEYCODE_STEM_PRIMARY                  = 264,
    MLKEYCODE_STEM_1                        = 265,
    MLKEYCODE_STEM_2                        = 266,
    MLKEYCODE_STEM_3                        = 267,
    MLKEYCODE_DPAD_UP_LEFT                  = 268,
    MLKEYCODE_DPAD_DOWN_LEFT                = 269,
    MLKEYCODE_DPAD_UP_RIGHT                 = 270,
    MLKEYCODE_DPAD_DOWN_RIGHT               = 271,
    MLKEYCODE_MEDIA_SKIP_FORWARD            = 272,
    MLKEYCODE_MEDIA_SKIP_BACKWARD           = 273,
    MLKEYCODE_MEDIA_STEP_FORWARD            = 274,
    MLKEYCODE_MEDIA_STEP_BACKWARD           = 275,
    MLKEYCODE_SOFT_SLEEP                    = 276,
    MLKEYCODE_CUT                           = 277,
    MLKEYCODE_COPY                          = 278,
    MLKEYCODE_PASTE                         = 279,
    MLKEYCODE_COUNT,
} MLKeyCode;

/*! Modifier keys defined for Magic Leap platform. */
typedef enum MLKeyModifier {
    MLKEYMODIFIER_ALT         = 0x02,
    MLKEYMODIFIER_ALT_LEFT    = 0x10,
    MLKEYMODIFIER_ALT_RIGHT   = 0x20,
    MLKEYMODIFIER_SHIFT       = 0x01,
    MLKEYMODIFIER_SHIFT_LEFT  = 0x40,
    MLKEYMODIFIER_SHIFT_RIGHT = 0x80,
    MLKEYMODIFIER_SYM         = 0x04,
    MLKEYMODIFIER_FUNCTION    = 0x08,
    MLKEYMODIFIER_CTRL        = 0x1000,
    MLKEYMODIFIER_CTRL_LEFT   = 0x2000,
    MLKEYMODIFIER_CTRL_RIGHT  = 0x4000,
    MLKEYMODIFIER_META        = 0x10000,
    MLKEYMODIFIER_META_LEFT   = 0x20000,
    MLKEYMODIFIER_META_RIGHT  = 0x40000,
    MLKEYMODIFIER_CAPS_LOCK   = 0x100000,
    MLKEYMODIFIER_NUM_LOCK    = 0x200000,
    MLKEYMODIFIER_SCROLL_LOCK = 0x400000,
} MLKeyModifier;

ML_EXTERN_C_END
